name: GitHub Classroom Workflow

on:
  push:
    branches:
    - '*'
    - '!badges'

permissions:
  contents: write

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      # add id to action so outputs can be used
      - uses: WCU-CS-CooperLab/autofeedback-s@v1.0
        id: autograder
        continue-on-error: true

      - uses: ebrain-lab/split-by@master
        id: split
        with:
           string: "${{ steps.autograder.outputs.points }}"
           split-by: '/'
      

      # make dir for badges
      - name: badges branch and make dir
        run: |
          git checkout badges 2>/dev/null || git checkout -b badges
          mkdir -p .github/badges
      # make tests passed badge
      - name: tests passed badge
        uses: emibcn/badge-action@v2.0.2
        id: pbadge
        with:
          label: 'Tests Passed'
          status: ${{ steps.autograder.outputs.points }}
          color: ${{
             steps.split.outputs._0 > 1 && 'green'               ||
             steps.split.outputs._0 > 1 && 'yellow,green' ||
             steps.split.outputs._0 > 1 && 'yellow,yellow,green' ||
             steps.split.outputs._0 > 1 && 'orange,yellow,yellow'  ||
             steps.split.outputs._0 > 0 && 'orange,orange,yellow'  ||
             'red' }}
          path: '.github/badges/points.svg'

      - name: Upload badge as artifact
        uses: actions/upload-artifact@v4
        with:
          name: badge
          path: '.github/badges/points.svg'
          if-no-files-found: error

      # commit and push badge if score has changed
      - name: Commit badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '.github/badges/points.svg'
          git commit -m "Add/Update badge"
        continue-on-error: true
      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: badges
          force: true
      - name: Check on failures
        if: steps.split.outputs._0 < 2
        run: echo "number of tessed passed ${{ steps.split.outputs._0 }},  ${{steps.autograder.outputs.points}} is under 2/2, Check Run WCU-CS-CooperLab/autofeedback-s@v1.0 for feedback. " && exit 1
